all: ex2.o solucao_ex2.c ex3.o solucao_ex3.c
	@echo "Testando ex2:"
	@gcc -Og solucao_ex2.c ex2.o -o ex2 && ./ex2
	@rm ex2

	@echo "Testando ex3:"
	@gcc -Og solucao_ex3.c ex3.o -o ex3 && ./ex3
	@rm ex3
